import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule, MatCardModule, MatDialogModule, MatInputModule, MatTableModule,
  MatToolbarModule, MatMenuModule, MatIconModule, MatDividerModule, MatRadioModule, MatProgressSpinnerModule,
  MatPaginatorModule, MatSortModule, MatTooltipModule, MatSelectModule, MatSidenavModule, MatCheckboxModule,
  MatBadgeModule, MatSnackBarModule, MatSlideToggleModule, MatGridListModule, MatListModule, MatChipsModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatIconModule,
    MatToolbarModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTableModule,
    MatMenuModule,
    MatIconModule,
    MatDividerModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatSortModule,
    MatTooltipModule,
    MatSelectModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatBadgeModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatListModule,
    MatChipsModule,
    MatSelectModule,
  ],
  exports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTableModule,
    MatMenuModule,
    MatIconModule,
    MatDividerModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatSortModule,
    MatTooltipModule,
    MatSelectModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatBadgeModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatGridListModule,
    MatListModule,
    MatChipsModule,
    MatSelectModule,
  ]
})
export class NgMaterialModule { }
